@host = http://localhost:5119

### User Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "jan.kowalski@gmail.com",
  "password": "SuperSecretPassword123!",
  "firstName": "Jan",
  "lastName": "Kowalski"
}

### User Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "jan.kowalski@gmail.com",
  "password": "SuperSecretPassword123!"
}