### Download available windows for a specific coach
GET {{host}}/api/bookings/coaches/{{coachId}}/slots
Authorization: Bearer {{userToken}}

> {%
    if (response.status === 200 && response.body.length > 0) {
        client.global.set("slotId", response.body[0].id);
    }
%}

### Book a slot as a member
POST {{host}}/api/bookings/trainer-slots/{{slotId}}
Authorization: Bearer {{userToken}}
Content-Type: application/json

### Download available classes
GET {{host}}/api/bookings/classes
Authorization: Bearer {{userToken}}
Accept: application/json

> {%
    if (response.status === 200 && response.body.length > 0) {
        client.global.set("classId", response.body[0].id);
    }
%}

### Book a class
POST {{host}}/api/bookings/classes/{{classId}}
Authorization: Bearer {{userToken}}
Content-Type: application/json

> {%
    if (response.status === 200) {
        client.global.set("reservationId", response.body.reservationId);
    }
%}

### Get my reservations (Will show 'Class Cancelled by Gym' if admin cancelled)
GET {{host}}/api/bookings/my-reservations
Authorization: Bearer {{userToken}}
Accept: application/json